JUCE: Array< ElementType, TypeOfCriticalSectionToUse > Class Template Reference
Array< ElementType, TypeOfCriticalSectionToUse > Class Template Reference
Holds a resizable array of primitive or copy-by-value objects.
Public Types
typedef
TypeOfCriticalSectionToUse::ScopedLockType ScopedLockType
Returns the type of scoped lock to use for locking this array.
Public Member Functions
Array () noexcept
Creates an empty array.
Array (const Array< ElementType, TypeOfCriticalSectionToUse > &other)
Creates a copy of another array.
template<typename TypeToCreateFrom >
Array (const TypeToCreateFrom *values)
Initalises from a null-terminated C array of values.
template<typename TypeToCreateFrom >
Array (const TypeToCreateFrom *values, int numValues)
Initalises from a C array of values.
~Array ()
Destructor.
Array & operator= (const Array &other)
Copies another array.
template<class OtherArrayType >
bool operator== (const OtherArrayType &other) const
Compares this array to another one.
template<class OtherArrayType >
bool operator!= (const OtherArrayType &other) const
Compares this array to another one.
void clear ()
Removes all elements from the array.
void clearQuick ()
Removes all elements from the array without freeing the array's allocated storage.
int size () const noexcept
Returns the current number of elements in the array.
ElementType operator[] (const int index) const
Returns one of the elements in the array.
ElementType getUnchecked (const int index) const
Returns one of the elements in the array, without checking the index passed in.
ElementType & getReference (const int index) const noexcept
Returns a direct reference to one of the elements in the array, without checking the index passed in.
ElementType getFirst () const
Returns the first element in the array, or 0 if the array is empty.
ElementType getLast () const
Returns the last element in the array, or 0 if the array is empty.
ElementType * getRawDataPointer () noexcept
Returns a pointer to the actual array data.
ElementType * begin () const noexcept
Returns a pointer to the first element in the array.
ElementType * end () const noexcept
Returns a pointer to the element which follows the last element in the array.
int indexOf (ParameterType elementToLookFor) const
Finds the index of the first element which matches the value passed in.
bool contains (ParameterType elementToLookFor) const
Returns true if the array contains at least one occurrence of an object.
void add (ParameterType newElement)
Appends a new element at the end of the array.
void insert (int indexToInsertAt, ParameterType newElement)
Inserts a new element into the array at a given position.
void insertMultiple (int indexToInsertAt, ParameterType newElement, int numberOfTimesToInsertIt)
Inserts multiple copies of an element into the array at a given position.
void insertArray (int indexToInsertAt, const ElementType *newElements, int numberOfElements)
Inserts an array of values into this array at a given position.
void addIfNotAlreadyThere (ParameterType newElement)
Appends a new element at the end of the array as long as the array doesn't already contain it.
void set (const int indexToChange, ParameterType newValue)
Replaces an element with a new value.
void setUnchecked (const int indexToChange, ParameterType newValue)
Replaces an element with a new value without doing any bounds-checking.
void addArray (const ElementType *elementsToAdd, int numElementsToAdd)
Adds elements from an array to the end of this array.
void swapWithArray (Array &otherArray) noexcept
This swaps the contents of this array with those of another array.
template<class OtherArrayType >
void addArray (const OtherArrayType &arrayToAddFrom, int startIndex=0, int numElementsToAdd=-1)
Adds elements from another array to the end of this array.
void resize (const int targetNumItems)
This will enlarge or shrink the array to the given number of elements, by adding or removing items from its end.
template<class ElementComparator >
int addSorted (ElementComparator &comparator, ParameterType newElement)
Inserts a new element into the array, assuming that the array is sorted.
void addUsingDefaultSort (ParameterType newElement)
Inserts a new element into the array, assuming that the array is sorted.
template<typename ElementComparator , typename TargetValueType >
int indexOfSorted (ElementComparator &comparator, TargetValueType elementToLookFor) const
Finds the index of an element in the array, assuming that the array is sorted.
ElementType remove (const int indexToRemove)
Removes an element from the array.
void removeFirstMatchingValue (ParameterType valueToRemove)
Removes an item from the array.
void removeAllInstancesOf (ParameterType valueToRemove)
Removes an item from the array.
void removeRange (int startIndex, int numberToRemove)
Removes a range of elements from the array.
void removeLast (int howManyToRemove=1)
Removes the last n elements from the array.
template<class OtherArrayType >
void removeValuesIn (const OtherArrayType &otherArray)
Removes any elements which are also in another array.
template<class OtherArrayType >
void removeValuesNotIn (const OtherArrayType &otherArray)
Removes any elements which are not found in another array.
void swap (const int index1, const int index2)
Swaps over two elements in the array.
void move (const int currentIndex, int newIndex) noexcept
Moves one of the values to a different position.
void minimiseStorageOverheads ()
Reduces the amount of storage being used by the array.
void ensureStorageAllocated (const int minNumElements)
Increases the array's internal storage to hold a minimum number of elements.
template<class ElementComparator >
void sort (ElementComparator &comparator, const bool retainOrderOfEquivalentItems=false) const
Sorts the elements in the array.
const TypeOfCriticalSectionToUse & getLock () const noexcept
Returns the CriticalSection that locks this array.
Detailed Description
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection>
class Array< ElementType, TypeOfCriticalSectionToUse >
Holds a resizable array of primitive or copy-by-value objects.
Examples of arrays are: Array<int>, Array<Rectangle> or Array<MyClass*>
The Array class can be used to hold simple, non-polymorphic objects as well as primitive types - to do so, the class must fulfil these requirements:
it must have a copy constructor and assignment operator
it must be able to be relocated in memory by a memcpy without this causing any problems - so objects whose functionality relies on external pointers or references to themselves can be used.
You can of course have an array of pointers to any kind of object, e.g. Array <MyClass*>, but if you do this, the array doesn't take any ownership of the objects - see the OwnedArray class or the ReferenceCountedArray class for more powerful ways of holding lists of objects.
For holding lists of strings, you can use Array<String>, but it's usually better to use the specialised class StringArray, which provides more useful functions.
To make all the array's methods thread-safe, pass in "CriticalSection" as the templated TypeOfCriticalSectionToUse parameter, instead of the default DummyCriticalSection.
See also:
OwnedArray, ReferenceCountedArray, StringArray, CriticalSection
Member Typedef Documentation
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> typedef TypeOfCriticalSectionToUse::ScopedLockType Array< ElementType, TypeOfCriticalSectionToUse >::ScopedLockType
Returns the type of scoped lock to use for locking this array.
Constructor & Destructor Documentation
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> Array< ElementType, TypeOfCriticalSectionToUse >::Array ()
Creates an empty array.
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> Array< ElementType, TypeOfCriticalSectionToUse >::Array (const Array< ElementType, TypeOfCriticalSectionToUse > & other)
Creates a copy of another array.
Parameters:
other the array to copy
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> template<typename TypeToCreateFrom > Array< ElementType, TypeOfCriticalSectionToUse >::Array (const TypeToCreateFrom * values) [explicit]
Initalises from a null-terminated C array of values.
Parameters:
values the array to copy from
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> template<typename TypeToCreateFrom > Array< ElementType, TypeOfCriticalSectionToUse >::Array (const TypeToCreateFrom * values, int numValues)
Initalises from a C array of values.
Parameters:
values the array to copy from
numValues the number of values in the array
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> Array< ElementType, TypeOfCriticalSectionToUse >::~Array ()
Destructor.
Member Function Documentation
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> Array& Array< ElementType, TypeOfCriticalSectionToUse >::operator= (const Array< ElementType, TypeOfCriticalSectionToUse > & other)
Copies another array.
Parameters:
other the array to copy
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> template<class OtherArrayType > bool Array< ElementType, TypeOfCriticalSectionToUse >::operator== (const OtherArrayType & other) const
Compares this array to another one.
Two arrays are considered equal if they both contain the same set of elements, in the same order.
Parameters:
other the other array to compare with
Referenced by Array< Glyph >::operator!=().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> template<class OtherArrayType > bool Array< ElementType, TypeOfCriticalSectionToUse >::operator!= (const OtherArrayType & other) const
Compares this array to another one.
Two arrays are considered equal if they both contain the same set of elements, in the same order.
Parameters:
other the other array to compare with
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> void Array< ElementType, TypeOfCriticalSectionToUse >::clear ()
Removes all elements from the array.
This will remove all the elements, and free any storage that the array is using. To clear the array without freeing the storage, use the clearQuick() method instead.
See also:
clearQuick
Referenced by SparseSet< int >::clear(), LassoComponent< SelectableItemType >::endLasso(), Array< Glyph >::removeValuesIn(), and Array< Glyph >::removeValuesNotIn().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> void Array< ElementType, TypeOfCriticalSectionToUse >::clearQuick ()
Removes all elements from the array without freeing the array's allocated storage.
See also:
clear
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> int Array< ElementType, TypeOfCriticalSectionToUse >::size () const
Returns the current number of elements in the array.
Referenced by HashMap< KeyType, ValueType, HashFunctionToUse, TypeOfCriticalSectionToUse >::clear(), SparseSet< int >::contains(), SparseSet< int >::getNumRanges(), HashMap< KeyType, ValueType, HashFunctionToUse, TypeOfCriticalSectionToUse >::getNumSlots(), SparseSet< int >::getTotalRange(), SparseSet< int >::isEmpty(), SparseSet< int >::operator[](), SparseSet< int >::removeRange(), SparseSet< int >::size(), and Array< Glyph >::sort().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> ElementType Array< ElementType, TypeOfCriticalSectionToUse >::operator[] (const int index) const
Returns one of the elements in the array.
If the index passed in is beyond the range of valid elements, this will return zero.
If you're certain that the index will always be a valid element, you can call getUnchecked() instead, which is faster.
Parameters:
index the index of the element being requested (0 is the first element in the array)
See also:
getUnchecked, getFirst, getLast
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> ElementType Array< ElementType, TypeOfCriticalSectionToUse >::getUnchecked (const int index) const
Returns one of the elements in the array, without checking the index passed in.
Unlike the operator[] method, this will try to return an element without checking that the index is within the bounds of the array, so should only be used when you're confident that it will always be a valid index.
Parameters:
index the index of the element being requested (0 is the first element in the array)
See also:
operator[], getFirst, getLast
Referenced by HashMap< KeyType, ValueType, HashFunctionToUse, TypeOfCriticalSectionToUse >::clear(), SparseSet< int >::contains(), HashMap< KeyType, ValueType, HashFunctionToUse, TypeOfCriticalSectionToUse >::contains(), SparseSet< int >::containsRange(), HashMap< KeyType, ValueType, HashFunctionToUse, TypeOfCriticalSectionToUse >::containsValue(), SparseSet< int >::getRange(), SparseSet< int >::getTotalRange(), HashMap< KeyType, ValueType, HashFunctionToUse, TypeOfCriticalSectionToUse >::Iterator::next(), SparseSet< int >::operator[](), HashMap< KeyType, ValueType, HashFunctionToUse, TypeOfCriticalSectionToUse >::operator[](), SparseSet< int >::overlapsRange(), HashMap< KeyType, ValueType, HashFunctionToUse, TypeOfCriticalSectionToUse >::remapTable(), HashMap< KeyType, ValueType, HashFunctionToUse, TypeOfCriticalSectionToUse >::remove(), SparseSet< int >::removeRange(), HashMap< KeyType, ValueType, HashFunctionToUse, TypeOfCriticalSectionToUse >::removeValue(), HashMap< KeyType, ValueType, HashFunctionToUse, TypeOfCriticalSectionToUse >::set(), and SparseSet< int >::size().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> ElementType& Array< ElementType, TypeOfCriticalSectionToUse >::getReference (const int index) const
Returns a direct reference to one of the elements in the array, without checking the index passed in.
This is like getUnchecked, but returns a direct reference to the element, so that you can alter it directly. Obviously this can be dangerous, so only use it when absolutely necessary.
Parameters:
index the index of the element being requested (0 is the first element in the array)
See also:
operator[], getFirst, getLast
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> ElementType Array< ElementType, TypeOfCriticalSectionToUse >::getFirst () const
Returns the first element in the array, or 0 if the array is empty.
See also:
operator[], getUnchecked, getLast
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> ElementType Array< ElementType, TypeOfCriticalSectionToUse >::getLast () const
Returns the last element in the array, or 0 if the array is empty.
See also:
operator[], getUnchecked, getFirst
Referenced by SparseSet< int >::removeRange().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> ElementType* Array< ElementType, TypeOfCriticalSectionToUse >::getRawDataPointer ()
Returns a pointer to the actual array data.
This pointer will only be valid until the next time a non-const method is called on the array.
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> ElementType* Array< ElementType, TypeOfCriticalSectionToUse >::begin () const
Returns a pointer to the first element in the array.
This method is provided for compatibility with standard C++ iteration mechanisms.
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> ElementType* Array< ElementType, TypeOfCriticalSectionToUse >::end () const
Returns a pointer to the element which follows the last element in the array.
This method is provided for compatibility with standard C++ iteration mechanisms.
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> int Array< ElementType, TypeOfCriticalSectionToUse >::indexOf (ParameterType elementToLookFor) const
Finds the index of the first element which matches the value passed in.
This will search the array for the given object, and return the index of its first occurrence. If the object isn't found, the method will return -1.
Parameters:
elementToLookFor the value or object to look for
Returns:
the index of the object, or -1 if it's not found
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> bool Array< ElementType, TypeOfCriticalSectionToUse >::contains (ParameterType elementToLookFor) const
Returns true if the array contains at least one occurrence of an object.
Parameters:
elementToLookFor the value or object to look for
Returns:
true if the item is found
Referenced by Array< Glyph >::addIfNotAlreadyThere().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> void Array< ElementType, TypeOfCriticalSectionToUse >::add (ParameterType newElement)
Appends a new element at the end of the array.
Parameters:
newElement the new object to add to the array
See also:
set, insert, addIfNotAlreadyThere, addSorted, addUsingDefaultSort, addArray
Referenced by Array< Glyph >::addArray(), Array< Glyph >::addIfNotAlreadyThere(), and Array< Glyph >::Array().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> void Array< ElementType, TypeOfCriticalSectionToUse >::insert (int indexToInsertAt, ParameterType newElement)
Inserts a new element into the array at a given position.
If the index is less than 0 or greater than the size of the array, the element will be added to the end of the array. Otherwise, it will be inserted into the array, moving all the later elements along to make room.
Parameters:
indexToInsertAt the index at which the new element should be inserted (pass in -1 to add it to the end)
newElement the new object to add to the array
See also:
add, addSorted, addUsingDefaultSort, set
Referenced by Array< Glyph >::addSorted().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> void Array< ElementType, TypeOfCriticalSectionToUse >::insertMultiple (int indexToInsertAt, ParameterType newElement, int numberOfTimesToInsertIt)
Inserts multiple copies of an element into the array at a given position.
If the index is less than 0 or greater than the size of the array, the element will be added to the end of the array. Otherwise, it will be inserted into the array, moving all the later elements along to make room.
Parameters:
indexToInsertAt the index at which the new element should be inserted
newElement the new object to add to the array
numberOfTimesToInsertIt how many copies of the value to insert
See also:
insert, add, addSorted, set
Referenced by HashMap< KeyType, ValueType, HashFunctionToUse, TypeOfCriticalSectionToUse >::HashMap(), and Array< Glyph >::resize().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> void Array< ElementType, TypeOfCriticalSectionToUse >::insertArray (int indexToInsertAt, const ElementType * newElements, int numberOfElements)
Inserts an array of values into this array at a given position.
If the index is less than 0 or greater than the size of the array, the new elements will be added to the end of the array. Otherwise, they will be inserted into the array, moving all the later elements along to make room.
Parameters:
indexToInsertAt the index at which the first new element should be inserted
newElements the new values to add to the array
numberOfElements how many items are in the array
See also:
insert, add, addSorted, set
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> void Array< ElementType, TypeOfCriticalSectionToUse >::addIfNotAlreadyThere (ParameterType newElement)
Appends a new element at the end of the array as long as the array doesn't already contain it.
If the array already contains an element that matches the one passed in, nothing will be done.
Parameters:
newElement the new object to add to the array
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> void Array< ElementType, TypeOfCriticalSectionToUse >::set (const int indexToChange, ParameterType newValue)
Replaces an element with a new value.
If the index is less than zero, this method does nothing. If the index is beyond the end of the array, the item is added to the end of the array.
Parameters:
indexToChange the index whose value you want to change
newValue the new value to set for this index.
See also:
add, insert
Referenced by HashMap< KeyType, ValueType, HashFunctionToUse, TypeOfCriticalSectionToUse >::clear(), HashMap< KeyType, ValueType, HashFunctionToUse, TypeOfCriticalSectionToUse >::remove(), HashMap< KeyType, ValueType, HashFunctionToUse, TypeOfCriticalSectionToUse >::removeValue(), and HashMap< KeyType, ValueType, HashFunctionToUse, TypeOfCriticalSectionToUse >::set().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> void Array< ElementType, TypeOfCriticalSectionToUse >::setUnchecked (const int indexToChange, ParameterType newValue)
Replaces an element with a new value without doing any bounds-checking.
This just sets a value directly in the array's internal storage, so you'd better make sure it's in range!
Parameters:
indexToChange the index whose value you want to change
newValue the new value to set for this index.
See also:
set, getUnchecked
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> void Array< ElementType, TypeOfCriticalSectionToUse >::addArray (const ElementType * elementsToAdd, int numElementsToAdd)
Adds elements from an array to the end of this array.
Parameters:
elementsToAdd the array of elements to add
numElementsToAdd how many elements are in this other array
See also:
add
Referenced by LassoComponent< SelectableItemType >::dragLasso().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> void Array< ElementType, TypeOfCriticalSectionToUse >::swapWithArray (Array< ElementType, TypeOfCriticalSectionToUse > & otherArray)
This swaps the contents of this array with those of another array.
If you need to exchange two arrays, this is vastly quicker than using copy-by-value because it just swaps their internal pointers.
Referenced by Array< Glyph >::operator=(), and HashMap< KeyType, ValueType, HashFunctionToUse, TypeOfCriticalSectionToUse >::swapWith().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> template<class OtherArrayType > void Array< ElementType, TypeOfCriticalSectionToUse >::addArray (const OtherArrayType & arrayToAddFrom, int startIndex = 0, int numElementsToAdd = -1)
Adds elements from another array to the end of this array.
Parameters:
arrayToAddFrom the array from which to copy the elements
startIndex the first element of the other array to start copying from
numElementsToAdd how many elements to add from the other array. If this value is negative or greater than the number of available elements, all available elements will be copied.
See also:
add
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> void Array< ElementType, TypeOfCriticalSectionToUse >::resize (const int targetNumItems)
This will enlarge or shrink the array to the given number of elements, by adding or removing items from its end.
If the array is smaller than the given target size, empty elements will be appended until its size is as specified. If its size is larger than the target, items will be removed from its end to shorten it.
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> template<class ElementComparator > int Array< ElementType, TypeOfCriticalSectionToUse >::addSorted (ElementComparator & comparator, ParameterType newElement)
Inserts a new element into the array, assuming that the array is sorted.
This will use a comparator to find the position at which the new element should go. If the array isn't sorted, the behaviour of this method will be unpredictable.
Parameters:
comparator the comparator to use to compare the elements - see the sort() method for details about the form this object should take
newElement the new element to insert to the array
Returns:
the index at which the new item was added
See also:
addUsingDefaultSort, add, sort
Referenced by Array< Glyph >::addUsingDefaultSort().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> void Array< ElementType, TypeOfCriticalSectionToUse >::addUsingDefaultSort (ParameterType newElement)
Inserts a new element into the array, assuming that the array is sorted.
This will use the DefaultElementComparator class for sorting, so your ElementType must be suitable for use with that class. If the array isn't sorted, the behaviour of this method will be unpredictable.
Parameters:
newElement the new element to insert to the array
See also:
addSorted, sort
Referenced by SparseSet< int >::addRange(), and SparseSet< int >::removeRange().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> template<typename ElementComparator , typename TargetValueType > int Array< ElementType, TypeOfCriticalSectionToUse >::indexOfSorted (ElementComparator & comparator, TargetValueType elementToLookFor) const
Finds the index of an element in the array, assuming that the array is sorted.
This will use a comparator to do a binary-chop to find the index of the given element, if it exists. If the array isn't sorted, the behaviour of this method will be unpredictable.
Parameters:
comparator the comparator to use to compare the elements - see the sort() method for details about the form this object should take
elementToLookFor the element to search for
Returns:
the index of the element, or -1 if it's not found
See also:
addSorted, sort
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> ElementType Array< ElementType, TypeOfCriticalSectionToUse >::remove (const int indexToRemove)
Removes an element from the array.
This will remove the element at a given index, and move back all the subsequent elements to close the gap. If the index passed in is out-of-range, nothing will happen.
Parameters:
indexToRemove the index of the element to remove
Returns:
the element that has been removed
See also:
removeValue, removeRange
Referenced by SparseSet< int >::removeRange().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> void Array< ElementType, TypeOfCriticalSectionToUse >::removeFirstMatchingValue (ParameterType valueToRemove)
Removes an item from the array.
This will remove the first occurrence of the given element from the array. If the item isn't found, no action is taken.
Parameters:
valueToRemove the object to try to remove
See also:
remove, removeRange
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> void Array< ElementType, TypeOfCriticalSectionToUse >::removeAllInstancesOf (ParameterType valueToRemove)
Removes an item from the array.
This will remove the first occurrence of the given element from the array. If the item isn't found, no action is taken.
Parameters:
valueToRemove the object to try to remove
See also:
remove, removeRange
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> void Array< ElementType, TypeOfCriticalSectionToUse >::removeRange (int startIndex, int numberToRemove)
Removes a range of elements from the array.
This will remove a set of elements, starting from the given index, and move subsequent elements down to close the gap.
If the range extends beyond the bounds of the array, it will be safely clipped to the size of the array.
Parameters:
startIndex the index of the first element to remove
numberToRemove how many elements should be removed
See also:
remove, removeValue
Referenced by Array< Glyph >::resize().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> void Array< ElementType, TypeOfCriticalSectionToUse >::removeLast (int howManyToRemove = 1)
Removes the last n elements from the array.
Parameters:
howManyToRemove how many elements to remove from the end of the array
See also:
remove, removeValue, removeRange
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> template<class OtherArrayType > void Array< ElementType, TypeOfCriticalSectionToUse >::removeValuesIn (const OtherArrayType & otherArray)
Removes any elements which are also in another array.
Parameters:
otherArray the other array in which to look for elements to remove
See also:
removeValuesNotIn, remove, removeValue, removeRange
Referenced by LassoComponent< SelectableItemType >::dragLasso().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> template<class OtherArrayType > void Array< ElementType, TypeOfCriticalSectionToUse >::removeValuesNotIn (const OtherArrayType & otherArray)
Removes any elements which are not found in another array.
Only elements which occur in this other array will be retained.
Parameters:
otherArray the array in which to look for elements NOT to remove
See also:
removeValuesIn, remove, removeValue, removeRange
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> void Array< ElementType, TypeOfCriticalSectionToUse >::swap (const int index1, const int index2)
Swaps over two elements in the array.
This swaps over the elements found at the two indexes passed in. If either index is out-of-range, this method will do nothing.
Parameters:
index1 index of one of the elements to swap
index2 index of the other element to swap
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> void Array< ElementType, TypeOfCriticalSectionToUse >::move (const int currentIndex, int newIndex)
Moves one of the values to a different position.
This will move the value to a specified index, shuffling along any intervening elements as required.
So for example, if you have the array { 0, 1, 2, 3, 4, 5 } then calling move (2, 4) would result in { 0, 1, 3, 4, 2, 5 }.
Parameters:
currentIndex the index of the value to be moved. If this isn't a valid index, then nothing will be done
newIndex the index at which you'd like this value to end up. If this is less than zero, the value will be moved to the end of the array
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> void Array< ElementType, TypeOfCriticalSectionToUse >::minimiseStorageOverheads ()
Reduces the amount of storage being used by the array.
Arrays typically allocate slightly more storage than they need, and after removing elements, they may have quite a lot of unused space allocated. This method will reduce the amount of allocated storage to a minimum.
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> void Array< ElementType, TypeOfCriticalSectionToUse >::ensureStorageAllocated (const int minNumElements)
Increases the array's internal storage to hold a minimum number of elements.
Calling this before adding a large known number of elements means that the array won't have to keep dynamically resizing itself as the elements are added, and it'll therefore be more efficient.
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> template<class ElementComparator > void Array< ElementType, TypeOfCriticalSectionToUse >::sort (ElementComparator & comparator, const bool retainOrderOfEquivalentItems = false) const
Sorts the elements in the array.
This will use a comparator object to sort the elements into order. The object passed must have a method of the form:
        int compareElements (ElementType first, ElementType second);
..and this method must return:
a value of < 0 if the first comes before the second
a value of 0 if the two objects are equivalent
a value of > 0 if the second comes before the first
To improve performance, the compareElements() method can be declared as static or const.
Parameters:
comparator the comparator to use for comparing elements.
retainOrderOfEquivalentItems if this is true, then items which the comparator says are equivalent will be kept in the order in which they currently appear in the array. This is slower to perform, but may be important in some cases. If it's false, a faster algorithm is used, but equivalent elements may be rearranged.
See also:
addSorted, indexOfSorted, sortArray
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection> const TypeOfCriticalSectionToUse& Array< ElementType, TypeOfCriticalSectionToUse >::getLock () const
Returns the CriticalSection that locks this array.
To lock, you can call getLock().enter() and getLock().exit(), or preferably use an object of ScopedLockType as an RAII lock for it.
Referenced by Array< Glyph >::add(), Array< Glyph >::addArray(), Array< Glyph >::addIfNotAlreadyThere(), Array< Glyph >::addSorted(), Array< Glyph >::Array(), Array< Glyph >::clear(), Array< Glyph >::clearQuick(), Array< Glyph >::contains(), Array< Glyph >::ensureStorageAllocated(), Array< Glyph >::getFirst(), Array< Glyph >::getLast(), Array< Glyph >::getReference(), Array< Glyph >::getUnchecked(), Array< Glyph >::indexOf(), Array< Glyph >::indexOfSorted(), Array< Glyph >::insert(), Array< Glyph >::insertArray(), Array< Glyph >::insertMultiple(), Array< Glyph >::minimiseStorageOverheads(), Array< Glyph >::move(), Array< Glyph >::operator==(), Array< Glyph >::operator[](), Array< Glyph >::remove(), Array< Glyph >::removeAllInstancesOf(), Array< Glyph >::removeFirstMatchingValue(), Array< Glyph >::removeLast(), Array< Glyph >::removeRange(), Array< Glyph >::removeValuesIn(), Array< Glyph >::removeValuesNotIn(), Array< Glyph >::set(), Array< Glyph >::setUnchecked(), Array< Glyph >::sort(), Array< Glyph >::swap(), and Array< Glyph >::swapWithArray().
The documentation for this class was generated from the following file:
juce_Array.h