JUCE: LassoComponent< SelectableItemType > Class Template Reference
LassoComponent< SelectableItemType > Class Template Reference
A component that acts as a rectangular selection region, which you drag with the mouse to select groups of objects (in conjunction with a SelectedItemSet).
Inherits Component.
Public Types
enum ColourIds { lassoFillColourId = 0x1000440, lassoOutlineColourId = 0x1000441 }
A set of colour IDs to use to change the colour of various aspects of the label.
Public Member Functions
LassoComponent (const int outlineThickness_=1)
Creates a Lasso component.
~LassoComponent ()
Destructor.
void beginLasso (const MouseEvent &e, LassoSource< SelectableItemType > *const lassoSource)
Call this in your mouseDown event, to initialise a drag.
void dragLasso (const MouseEvent &e)
Call this in your mouseDrag event, to update the lasso's position.
void endLasso ()
Call this in your mouseUp event, after the lasso has been dragged.
void paint (Graphics &g)
bool hitTest (int, int)
Detailed Description
template<class SelectableItemType>
class LassoComponent< SelectableItemType >
A component that acts as a rectangular selection region, which you drag with the mouse to select groups of objects (in conjunction with a SelectedItemSet).
To use one of these:
In your mouseDown or mouseDrag event, add the LassoComponent to your parent component, and call its beginLasso() method, giving it a suitable LassoSource object that it can use to find out which items are in the active area.
Each time your parent component gets a mouseDrag event, call dragLasso() to update the lasso's position - it will use its LassoSource to calculate and update the current selection.
After the drag has finished and you get a mouseUp callback, you should call endLasso() to clean up. This will make the lasso component invisible, and you can remove it from the parent component, or delete it.
The class takes into account the modifier keys that are being held down while the lasso is being dragged, so if shift is pressed, then any lassoed items will be added to the original selection; if ctrl or command is pressed, they will be xor'ed with any previously selected items.
See also:
LassoSource, SelectedItemSet
Member Enumeration Documentation
template<class SelectableItemType > enum LassoComponent::ColourIds
A set of colour IDs to use to change the colour of various aspects of the label.
These constants can be used either via the Component::setColour(), or LookAndFeel::setColour() methods.
Note that you can also use the constants from TextEditor::ColourIds to change the colour of the text editor that is opened when a label is editable.
See also:
Component::setColour, Component::findColour, LookAndFeel::setColour, LookAndFeel::findColour
Enumerator:
lassoFillColourId
The colour to fill the lasso rectangle with.
lassoOutlineColourId
The colour to draw the outline with.
Constructor & Destructor Documentation
template<class SelectableItemType > LassoComponent< SelectableItemType >::LassoComponent (const int outlineThickness_ = 1) [explicit]
Creates a Lasso component.
The fill colour is used to fill the lasso'ed rectangle, and the outline colour is used to draw a line around its edge.
template<class SelectableItemType > LassoComponent< SelectableItemType >::~LassoComponent ()
Destructor.
Member Function Documentation
template<class SelectableItemType > void LassoComponent< SelectableItemType >::beginLasso (const MouseEvent & e, LassoSource< SelectableItemType > *const lassoSource)
Call this in your mouseDown event, to initialise a drag.
Pass in a suitable LassoSource object which the lasso will use to find the items and change the selection.
After using this method to initialise the lasso, repeatedly call dragLasso() in your component's mouseDrag callback.
See also:
dragLasso, endLasso, LassoSource
References LassoSource< SelectableItemType >::getLassoSelection(), MouseEvent::getMouseDownPosition(), Component::getParentComponent(), jassert, and Component::setSize().
template<class SelectableItemType > void LassoComponent< SelectableItemType >::dragLasso (const MouseEvent & e)
Call this in your mouseDrag event, to update the lasso's position.
This must be repeatedly calling when the mouse is dragged, after you've first initialised the lasso with beginLasso().
This method takes into account the modifier keys that are being held down, so if shift is pressed, then the lassoed items will be added to any that were previously selected; if ctrl or command is pressed, then they will be xor'ed with previously selected items.
See also:
beginLasso, endLasso
References Array< ElementType, TypeOfCriticalSectionToUse >::addArray(), Component::getBounds(), MouseEvent::getPosition(), ModifierKeys::isAltDown(), ModifierKeys::isCommandDown(), ModifierKeys::isShiftDown(), MouseEvent::mods, Array< ElementType, TypeOfCriticalSectionToUse >::removeValuesIn(), Component::setBounds(), and Component::setVisible().
template<class SelectableItemType > void LassoComponent< SelectableItemType >::endLasso ()
Call this in your mouseUp event, after the lasso has been dragged.
See also:
beginLasso, dragLasso
References Array< ElementType, TypeOfCriticalSectionToUse >::clear(), and Component::setVisible().
template<class SelectableItemType > void LassoComponent< SelectableItemType >::paint (Graphics & g) [virtual]
Reimplemented from Component.
References Graphics::drawRect(), Graphics::fillAll(), Component::findColour(), Component::getHeight(), Component::getWidth(), Component::isMouseButtonDownAnywhere(), jassert, LassoComponent< SelectableItemType >::lassoFillColourId, LassoComponent< SelectableItemType >::lassoOutlineColourId, and Graphics::setColour().
template<class SelectableItemType > bool LassoComponent< SelectableItemType >::hitTest (int , int) [virtual]
Reimplemented from Component.
The documentation for this class was generated from the following file:
juce_LassoComponent.h