JUCE: JUCEApplication Class Reference
JUCEApplication Class Reference
An instance of this class is used to specify initialisation and shutdown code for the application.
Inherits JUCEApplicationBase, and ApplicationCommandTarget.
Public Member Functions
virtual ~JUCEApplication ()
Destructor.
bool isInitialising () const noexcept
Returns true if the application hasn't yet completed its initialise() method and entered the main event loop.
virtual const String getApplicationName ()=0
Returns the application's name.
virtual const String getApplicationVersion ()=0
Returns the application's version number.
virtual bool moreThanOneInstanceAllowed ()
Checks whether multiple instances of the app are allowed.
virtual void anotherInstanceStarted (const String &commandLine)
Indicates that the user has tried to start up another instance of the app.
virtual void systemRequestedQuit ()
Called when the operating system is trying to close the application.
virtual void suspended ()
This method is called when the application is being put into background mode by the operating system.
virtual void resumed ()
This method is called when the application is being woken from background mode by the operating system.
virtual void unhandledException (const std::exception *e, const String &sourceFilename, int lineNumber)
If any unhandled exceptions make it through to the message dispatch loop, this callback will be triggered, in case you want to log them or do some other type of error-handling.
void setApplicationReturnValue (int newReturnValue) noexcept
Sets the value that should be returned as the application's exit code when the app quits.
int getApplicationReturnValue () const noexcept
Returns the value that has been set as the application's exit code.
ApplicationCommandTarget * getNextCommandTarget ()
void getCommandInfo (CommandID, ApplicationCommandInfo &)
void getAllCommands (Array< CommandID > &)
bool perform (const InvocationInfo &)
Static Public Member Functions
static JUCEApplication * getInstance () noexcept
Returns the global instance of the application object being run.
static void quit ()
Signals that the main message loop should stop and the application should terminate.
static StringArray JUCE_CALLTYPE getCommandLineParameterArray ()
Returns the application's command line parameters as a set of strings.
static String JUCE_CALLTYPE getCommandLineParameters ()
Returns the application's command line parameters as a single string.
static bool isStandaloneApp () noexcept
Returns true if this executable is running as an app (as opposed to being a plugin or other kind of shared library.
Protected Member Functions
JUCEApplication ()
Constructs a JUCE app object.
Detailed Description
An instance of this class is used to specify initialisation and shutdown code for the application.
An application that wants to run in the JUCE framework needs to declare a subclass of JUCEApplication and implement its various pure virtual methods.
It then needs to use the START_JUCE_APPLICATION macro somewhere in a cpp file to declare an instance of this class and generate a suitable platform-specific main() function.
e.g.
        class MyJUCEApp  : public JUCEApplication
        {
        public:
            MyJUCEApp()
            {
            }
            ~MyJUCEApp()
            {
            }
            void initialise (const String& commandLine)
            {
                myMainWindow = new MyApplicationWindow();
                myMainWindow->setBounds (100, 100, 400, 500);
                myMainWindow->setVisible (true);
            }
            void shutdown()
            {
                myMainWindow = 0;
            }
            const String getApplicationName()
            {
                return "Super JUCE-o-matic";
            }
            const String getApplicationVersion()
            {
                return "1.0";
            }
        private:
            ScopedPointer <MyApplicationWindow> myMainWindow;
        };
        // this creates wrapper code to actually launch the app properly.
        START_JUCE_APPLICATION (MyJUCEApp)
See also:
MessageManager
Constructor & Destructor Documentation
JUCEApplication::JUCEApplication () [protected]
Constructs a JUCE app object.
If subclasses implement a constructor or destructor, they shouldn't call any JUCE code in there - put your startup/shutdown code in initialise() and shutdown() instead.
virtual JUCEApplication::~JUCEApplication () [virtual]
Destructor.
If subclasses implement a constructor or destructor, they shouldn't call any JUCE code in there - put your startup/shutdown code in initialise() and shutdown() instead.
Member Function Documentation
static JUCEApplication* JUCEApplication::getInstance () [static]
Returns the global instance of the application object being run.
Reimplemented from JUCEApplicationBase.
References JUCEApplicationBase::getInstance().
bool JUCEApplication::isInitialising () const
Returns true if the application hasn't yet completed its initialise() method and entered the main event loop.
This is handy for things like splash screens to know when the app's up-and-running properly.
virtual const String JUCEApplication::getApplicationName () [pure virtual]
Returns the application's name.
An application must implement this to name itself.
Implements JUCEApplicationBase.
virtual const String JUCEApplication::getApplicationVersion () [pure virtual]
Returns the application's version number.
Implements JUCEApplicationBase.
virtual bool JUCEApplication::moreThanOneInstanceAllowed () [virtual]
Checks whether multiple instances of the app are allowed.
If you application class returns true for this, more than one instance is permitted to run (except on OSX where the OS automatically stops you launching a second instance of an app without explicitly starting it from the command-line).
If it's false, the second instance won't start, but it you will still get a callback to anotherInstanceStarted() to tell you about this - which gives you a chance to react to what the user was trying to do.
Implements JUCEApplicationBase.
virtual void JUCEApplication::anotherInstanceStarted (const String & commandLine) [virtual]
Indicates that the user has tried to start up another instance of the app.
This will get called even if moreThanOneInstanceAllowed() is false.
Implements JUCEApplicationBase.
virtual void JUCEApplication::systemRequestedQuit () [virtual]
Called when the operating system is trying to close the application.
The default implementation of this method is to call quit(), but it may be overloaded to ignore the request or do some other special behaviour instead. For example, you might want to offer the user the chance to save their changes before quitting, and give them the chance to cancel.
If you want to send a quit signal to your app, this is the correct method to call, because it means that requests that come from the system get handled in the same way as those from your own application code. So e.g. you'd call this method from a "quit" item on a menu bar.
Implements JUCEApplicationBase.
virtual void JUCEApplication::suspended () [virtual]
This method is called when the application is being put into background mode by the operating system.
Implements JUCEApplicationBase.
virtual void JUCEApplication::resumed () [virtual]
This method is called when the application is being woken from background mode by the operating system.
Implements JUCEApplicationBase.
virtual void JUCEApplication::unhandledException (const std::exception * e, const String & sourceFilename, int lineNumber) [virtual]
If any unhandled exceptions make it through to the message dispatch loop, this callback will be triggered, in case you want to log them or do some other type of error-handling.
If the type of exception is derived from the std::exception class, the pointer passed-in will be valid. If the exception is of unknown type, this pointer will be null.
Implements JUCEApplicationBase.
static void JUCEApplication::quit () [static]
Signals that the main message loop should stop and the application should terminate.
This isn't synchronous, it just posts a quit message to the main queue, and when this message arrives, the message loop will stop, the shutdown() method will be called, and the app will exit.
Note that this will cause an unconditional quit to happen, so if you need an extra level before this, e.g. to give the user the chance to save their work and maybe cancel the quit, you'll need to handle this in the systemRequestedQuit() method - see that method's help for more info.
See also:
MessageManager
Referenced by StandaloneFilterWindow::closeButtonPressed(), and StandaloneFilterWindow::StandaloneFilterWindow().
void JUCEApplication::setApplicationReturnValue (int newReturnValue)
Sets the value that should be returned as the application's exit code when the app quits.
This is the value that's returned by the main() function. Normally you'd leave this as 0 unless you want to indicate an error code.
See also:
getApplicationReturnValue
int JUCEApplication::getApplicationReturnValue () const
Returns the value that has been set as the application's exit code.
See also:
setApplicationReturnValue
static StringArray JUCE_CALLTYPE JUCEApplication::getCommandLineParameterArray () [static]
Returns the application's command line parameters as a set of strings.
See also:
getCommandLineParameters
static String JUCE_CALLTYPE JUCEApplication::getCommandLineParameters () [static]
Returns the application's command line parameters as a single string.
See also:
getCommandLineParameterArray
static bool JUCEApplication::isStandaloneApp () [static]
Returns true if this executable is running as an app (as opposed to being a plugin or other kind of shared library.
Reimplemented from JUCEApplicationBase.
ApplicationCommandTarget* JUCEApplication::getNextCommandTarget () [virtual]
Implements ApplicationCommandTarget.
void JUCEApplication::getCommandInfo (CommandID , ApplicationCommandInfo &) [virtual]
Implements ApplicationCommandTarget.
void JUCEApplication::getAllCommands (Array< CommandID > &) [virtual]
Implements ApplicationCommandTarget.
bool JUCEApplication::perform (const InvocationInfo &) [virtual]
Implements ApplicationCommandTarget.
The documentation for this class was generated from the following file:
juce_Application.h