JUCE: ResizableWindow Class Reference
ResizableWindow Class Reference
A base class for top-level windows that can be dragged around and resized.
Inherits TopLevelWindow.
Inherited by DocumentWindow, and FileChooserDialogBox.
Public Types
enum ColourIds { backgroundColourId = 0x1005700 }
A set of colour IDs to use to change the colour of various aspects of the window.
Public Member Functions
ResizableWindow (const String &name, bool addToDesktop)
Creates a ResizableWindow.
ResizableWindow (const String &name, const Colour &backgroundColour, bool addToDesktop)
Creates a ResizableWindow.
~ResizableWindow ()
Destructor.
Colour getBackgroundColour () const noexcept
Returns the colour currently being used for the window's background.
void setBackgroundColour (const Colour &newColour)
Changes the colour currently being used for the window's background.
void setResizable (bool shouldBeResizable, bool useBottomRightCornerResizer)
Make the window resizable or fixed.
bool isResizable () const noexcept
True if resizing is enabled.
void setResizeLimits (int newMinimumWidth, int newMinimumHeight, int newMaximumWidth, int newMaximumHeight) noexcept
This sets the maximum and minimum sizes for the window.
ComponentBoundsConstrainer * getConstrainer () noexcept
Returns the bounds constrainer object that this window is using.
void setConstrainer (ComponentBoundsConstrainer *newConstrainer)
Sets the bounds-constrainer object to use for resizing and dragging this window.
void setBoundsConstrained (const Rectangle< int > &bounds)
Calls the window's setBounds method, after first checking these bounds with the current constrainer.
bool isFullScreen () const
Returns true if the window is currently in full-screen mode.
void setFullScreen (bool shouldBeFullScreen)
Puts the window into full-screen mode, or restores it to its normal size.
bool isMinimised () const
Returns true if the window is currently minimised.
void setMinimised (bool shouldMinimise)
Minimises the window, or restores it to its previous position and size.
void addToDesktop ()
Adds the window to the desktop using the default flags.
String getWindowStateAsString ()
Returns a string which encodes the window's current size and position.
bool restoreWindowStateFromString (const String &previousState)
Restores the window to a previously-saved size and position.
Component * getContentComponent () const noexcept
Returns the current content component.
void setContentOwned (Component *newContentComponent, bool resizeToFitWhenContentChangesSize)
Changes the current content component.
void setContentNonOwned (Component *newContentComponent, bool resizeToFitWhenContentChangesSize)
Changes the current content component.
void clearContentComponent ()
Removes the current content component.
void setContentComponentSize (int width, int height)
Changes the window so that the content component ends up with the specified size.
virtual BorderSize< int > getBorderThickness ()
Returns the width of the frame to use around the window.
virtual BorderSize< int > getContentComponentBorder ()
Returns the insets to use when positioning the content component.
JUCE_DEPRECATED (void setContentComponent(Component *newContentComponent, bool deleteOldOne=true, bool resizeToFit=false))
Public Member Functions inherited from TopLevelWindow
TopLevelWindow (const String &name, bool addToDesktop)
Creates a TopLevelWindow.
~TopLevelWindow ()
Destructor.
bool isActiveWindow () const noexcept
True if this is currently the TopLevelWindow that is actively being used.
void centreAroundComponent (Component *componentToCentreAround, int width, int height)
This will set the bounds of the window so that it's centred in front of another window.
void setDropShadowEnabled (bool useShadow)
Turns the drop-shadow on and off.
bool isDropShadowEnabled () const noexcept
True if drop-shadowing is enabled.
void setUsingNativeTitleBar (bool useNativeTitleBar)
Sets whether an OS-native title bar will be used, or a Juce one.
bool isUsingNativeTitleBar () const noexcept
Returns true if the window is currently using an OS-native title bar.
virtual void addToDesktop (int windowStyleFlags, void *nativeWindowToAttachTo=nullptr)
Public Member Functions inherited from Component
Component ()
Creates a component.
virtual ~Component ()
Destructor.
Component (const String &componentName)
Creates a component, setting its name at the same time.
const String & getName () const noexcept
Returns the name of this component.
virtual void setName (const String &newName)
Sets the name of this component.
const String & getComponentID () const noexcept
Returns the ID string that was set by setComponentID().
void setComponentID (const String &newID)
Sets the component's ID string.
virtual void setVisible (bool shouldBeVisible)
Makes the component visible or invisible.
bool isVisible () const noexcept
Tests whether the component is visible or not.
bool isShowing () const
Tests whether this component and all its parents are visible.
void removeFromDesktop ()
If the component is currently showing on the desktop, this will hide it.
bool isOnDesktop () const noexcept
Returns true if this component is currently showing on the desktop.
ComponentPeer * getPeer () const
Returns the heavyweight window that contains this component.
virtual void userTriedToCloseWindow ()
For components on the desktop, this is called if the system wants to close the window.
virtual void minimisationStateChanged (bool isNowMinimised)
Called for a desktop component which has just been minimised or un-minimised.
void toFront (bool shouldAlsoGainFocus)
Brings the component to the front of its siblings.
void toBack ()
Changes this component's z-order to be at the back of all its siblings.
void toBehind (Component *other)
Changes this component's z-order so that it's just behind another component.
void setAlwaysOnTop (bool shouldStayOnTop)
Sets whether the component should always be kept at the front of its siblings.
bool isAlwaysOnTop () const noexcept
Returns true if this component is set to always stay in front of its siblings.
int getX () const noexcept
Returns the x coordinate of the component's left edge.
int getY () const noexcept
Returns the y coordinate of the top of this component.
int getWidth () const noexcept
Returns the component's width in pixels.
int getHeight () const noexcept
Returns the component's height in pixels.
int getRight () const noexcept
Returns the x coordinate of the component's right-hand edge.
const Point< int > & getPosition () const noexcept
Returns the component's top-left position as a Point.
int getBottom () const noexcept
Returns the y coordinate of the bottom edge of this component.
const Rectangle< int > & getBounds () const noexcept
Returns this component's bounding box.
Rectangle< int > getLocalBounds () const noexcept
Returns the component's bounds, relative to its own origin.
Rectangle< int > getBoundsInParent () const noexcept
Returns the area of this component's parent which this component covers.
void getVisibleArea (RectangleList &result, bool includeSiblings) const
Returns the region of this component that's not obscured by other, opaque components.
int getScreenX () const
Returns this component's x coordinate relative the the screen's top-left origin.
int getScreenY () const
Returns this component's y coordinate relative the the screen's top-left origin.
Point< int > getScreenPosition () const
Returns the position of this component's top-left corner relative to the screen's top-left.
Rectangle< int > getScreenBounds () const
Returns the bounds of this component, relative to the screen's top-left.
Point< int > getLocalPoint (const Component *sourceComponent, const Point< int > &pointRelativeToSourceComponent) const
Converts a point to be relative to this component's coordinate space.
Rectangle< int > getLocalArea (const Component *sourceComponent, const Rectangle< int > &areaRelativeToSourceComponent) const
Converts a rectangle to be relative to this component's coordinate space.
Point< int > localPointToGlobal (const Point< int > &localPoint) const
Converts a point relative to this component's top-left into a screen coordinate.
Rectangle< int > localAreaToGlobal (const Rectangle< int > &localArea) const
Converts a rectangle from this component's coordinate space to a screen coordinate.
void setTopLeftPosition (int x, int y)
Moves the component to a new position.
void setTopLeftPosition (const Point< int > &newTopLeftPosition)
Moves the component to a new position.
void setTopRightPosition (int x, int y)
Moves the component to a new position.
void setSize (int newWidth, int newHeight)
Changes the size of the component.
void setBounds (int x, int y, int width, int height)
Changes the component's position and size.
void setBounds (const Rectangle< int > &newBounds)
Changes the component's position and size.
void setBounds (const RelativeRectangle &newBounds)
Changes the component's position and size.
void setBounds (const String &newBoundsExpression)
Sets the component's bounds with an expression.
void setBoundsRelative (float proportionalX, float proportionalY, float proportionalWidth, float proportionalHeight)
Changes the component's position and size in terms of fractions of its parent's size.
void setBoundsInset (const BorderSize< int > &borders)
Changes the component's position and size based on the amount of space to leave around it.
void setBoundsToFit (int x, int y, int width, int height, const Justification &justification, bool onlyReduceInSize)
Positions the component within a given rectangle, keeping its proportions unchanged.
void setCentrePosition (int x, int y)
Changes the position of the component's centre.
void setCentreRelative (float x, float y)
Changes the position of the component's centre.
void centreWithSize (int width, int height)
Changes the component's size and centres it within its parent.
void setTransform (const AffineTransform &transform)
Sets a transform matrix to be applied to this component.
AffineTransform getTransform () const
Returns the transform that is currently being applied to this component.
bool isTransformed () const noexcept
Returns true if a non-identity transform is being applied to this component.
int proportionOfWidth (float proportion) const noexcept
Returns a proportion of the component's width.
int proportionOfHeight (float proportion) const noexcept
Returns a proportion of the component's height.
int getParentWidth () const noexcept
Returns the width of the component's parent.
int getParentHeight () const noexcept
Returns the height of the component's parent.
Rectangle< int > getParentMonitorArea () const
Returns the screen coordinates of the monitor that contains this component.
int getNumChildComponents () const noexcept
Returns the number of child components that this component contains.
Component * getChildComponent (int index) const noexcept
Returns one of this component's child components, by it index.
int getIndexOfChildComponent (const Component *child) const noexcept
Returns the index of this component in the list of child components.
Component * findChildWithID (const String &componentID) const noexcept
Looks for a child component with the specified ID.
void addChildComponent (Component *child, int zOrder=-1)
Adds a child component to this one.
void addAndMakeVisible (Component *child, int zOrder=-1)
Adds a child component to this one, and also makes the child visible if it isn't.
void addChildAndSetID (Component *child, const String &componentID)
Adds a child component to this one, makes it visible, and sets its component ID.
void removeChildComponent (Component *childToRemove)
Removes one of this component's child-components.
Component * removeChildComponent (int childIndexToRemove)
Removes one of this component's child-components by index.
void removeAllChildren ()
Removes all this component's children.
void deleteAllChildren ()
Removes all this component's children, and deletes them.
Component * getParentComponent () const noexcept
Returns the component which this component is inside.
template<class TargetClass >
TargetClass * findParentComponentOfClass () const
Searches the parent components for a component of a specified class.
Component * getTopLevelComponent () const noexcept
Returns the highest-level component which contains this one or its parents.
bool isParentOf (const Component *possibleChild) const noexcept
Checks whether a component is anywhere inside this component or its children.
virtual void childrenChanged ()
Subclasses can use this callback to be told when children are added or removed, or when their z-order changes.
virtual bool hitTest (int x, int y)
Tests whether a given point inside the component.
void setInterceptsMouseClicks (bool allowClicksOnThisComponent, bool allowClicksOnChildComponents) noexcept
Changes the default return value for the hitTest() method.
void getInterceptsMouseClicks (bool &allowsClicksOnThisComponent, bool &allowsClicksOnChildComponents) const noexcept
Retrieves the current state of the mouse-click interception flags.
bool contains (const Point< int > &localPoint)
Returns true if a given point lies within this component or one of its children.
bool reallyContains (const Point< int > &localPoint, bool returnTrueIfWithinAChild)
Returns true if a given point lies in this component, taking any overlapping siblings into account.
Component * getComponentAt (int x, int y)
Returns the component at a certain point within this one.
Component * getComponentAt (const Point< int > &position)
Returns the component at a certain point within this one.
void repaint ()
Marks the whole component as needing to be redrawn.
void repaint (int x, int y, int width, int height)
Marks a subsection of this component as needing to be redrawn.
void repaint (const Rectangle< int > &area)
Marks a subsection of this component as needing to be redrawn.
void setBufferedToImage (bool shouldBeBuffered)
Makes the component use an internal buffer to optimise its redrawing.
Image createComponentSnapshot (const Rectangle< int > &areaToGrab, bool clipImageToComponentBounds=true)
Generates a snapshot of part of this component.
void paintEntireComponent (Graphics &context, bool ignoreAlphaLevel)
Draws this component and all its subcomponents onto the specified graphics context.
void setPaintingIsUnclipped (bool shouldPaintWithoutClipping) noexcept
This allows you to indicate that this component doesn't require its graphics context to be clipped when it is being painted.
void setComponentEffect (ImageEffectFilter *newEffect)
Adds an effect filter to alter the component's appearance.
ImageEffectFilter * getComponentEffect () const noexcept
Returns the current component effect.
LookAndFeel & getLookAndFeel () const noexcept
Finds the appropriate look-and-feel to use for this component.
void setLookAndFeel (LookAndFeel *newLookAndFeel)
Sets the look and feel to use for this component.
void sendLookAndFeelChange ()
Calls the lookAndFeelChanged() method in this component and all its children.
void setOpaque (bool shouldBeOpaque)
Indicates whether any parts of the component might be transparent.
bool isOpaque () const noexcept
Returns true if no parts of this component are transparent.
void setBroughtToFrontOnMouseClick (bool shouldBeBroughtToFront) noexcept
Indicates whether the component should be brought to the front when clicked.
bool isBroughtToFrontOnMouseClick () const noexcept
Indicates whether the component should be brought to the front when clicked-on.
void setWantsKeyboardFocus (bool wantsFocus) noexcept
Sets a flag to indicate whether this component needs keyboard focus or not.
bool getWantsKeyboardFocus () const noexcept
Returns true if the component is interested in getting keyboard focus.
void setMouseClickGrabsKeyboardFocus (bool shouldGrabFocus)
Chooses whether a click on this component automatically grabs the focus.
bool getMouseClickGrabsKeyboardFocus () const noexcept
Returns the last value set with setMouseClickGrabsKeyboardFocus().
void grabKeyboardFocus ()
Tries to give keyboard focus to this component.
bool hasKeyboardFocus (bool trueIfChildIsFocused) const
Returns true if this component currently has the keyboard focus.
void moveKeyboardFocusToSibling (bool moveToNext)
Tries to move the keyboard focus to one of this component's siblings.
virtual KeyboardFocusTraverser * createFocusTraverser ()
Creates a KeyboardFocusTraverser object to use to determine the logic by which focus should be passed from this component.
int getExplicitFocusOrder () const
Returns the focus order of this component, if one has been specified.
void setExplicitFocusOrder (int newFocusOrderIndex)
Sets the index used in determining the order in which focusable components should be traversed.
void setFocusContainer (bool shouldBeFocusContainer) noexcept
Indicates whether this component is a parent for components that can have their focus traversed.
bool isFocusContainer () const noexcept
Returns true if this component has been marked as a focus container.
bool isEnabled () const noexcept
Returns true if the component (and all its parents) are enabled.
void setEnabled (bool shouldBeEnabled)
Enables or disables this component.
virtual void enablementChanged ()
Callback to indicate that this component has been enabled or disabled.
void setAlpha (float newAlpha)
Changes the transparency of this component.
float getAlpha () const
Returns the component's current transparancy level.
void setMouseCursor (const MouseCursor &cursorType)
Changes the mouse cursor shape to use when the mouse is over this component.
virtual MouseCursor getMouseCursor ()
Returns the mouse cursor shape to use when the mouse is over this component.
void updateMouseCursor () const
Forces the current mouse cursor to be updated.
virtual void paintOverChildren (Graphics &g)
Components can override this method to draw over the top of their children.
virtual void mouseMove (const MouseEvent &event)
Called when the mouse moves inside a component.
virtual void mouseEnter (const MouseEvent &event)
Called when the mouse first enters a component.
virtual void mouseExit (const MouseEvent &event)
Called when the mouse moves out of a component.
virtual void mouseUp (const MouseEvent &event)
Called when a mouse button is released.
virtual void mouseDoubleClick (const MouseEvent &event)
Called when a mouse button has been double-clicked on a component.
virtual void mouseWheelMove (const MouseEvent &event, const MouseWheelDetails &wheel)
Called when the mouse-wheel is moved.
virtual void mouseMagnify (const MouseEvent &event, float scaleFactor)
Called when a pinch-to-zoom mouse-gesture is used.
void setRepaintsOnMouseActivity (bool shouldRepaint) noexcept
Causes automatic repaints when the mouse enters or exits this component.
void addMouseListener (MouseListener *newListener, bool wantsEventsForAllNestedChildComponents)
Registers a listener to be told when mouse events occur in this component.
void removeMouseListener (MouseListener *listenerToRemove)
Deregisters a mouse listener.
void addKeyListener (KeyListener *newListener)
Adds a listener that wants to hear about keypresses that this component receives.
void removeKeyListener (KeyListener *listenerToRemove)
Removes a previously-registered key listener.
virtual bool keyPressed (const KeyPress &key)
Called when a key is pressed.
virtual bool keyStateChanged (bool isKeyDown)
Called when a key is pressed or released.
virtual void modifierKeysChanged (const ModifierKeys &modifiers)
Called when a modifier key is pressed or released.
virtual void focusGained (FocusChangeType cause)
Called to indicate that this component has just acquired the keyboard focus.
virtual void focusLost (FocusChangeType cause)
Called to indicate that this component has just lost the keyboard focus.
bool isMouseOver (bool includeChildren=false) const
Returns true if the mouse is currently over this component.
bool isMouseButtonDown () const
Returns true if the mouse button is currently held down in this component.
bool isMouseOverOrDragging () const
True if the mouse is over this component, or if it's being dragged in this component.
Point< int > getMouseXYRelative () const
Returns the mouse's current position, relative to this component.
virtual void broughtToFront ()
Called when this component has been moved to the front of its siblings.
void addComponentListener (ComponentListener *newListener)
Adds a listener to be told about changes to the component hierarchy or position.
void removeComponentListener (ComponentListener *listenerToRemove)
Removes a component listener.
void postCommandMessage (int commandId)
Dispatches a numbered message to this component.
virtual void handleCommandMessage (int commandId)
Called to handle a command that was sent by postCommandMessage().
void enterModalState (bool takeKeyboardFocus=true, ModalComponentManager::Callback *callback=nullptr, bool deleteWhenDismissed=false)
Runs a component modally, waiting until the loop terminates.
void exitModalState (int returnValue)
Ends a component's modal state.
bool isCurrentlyModal () const noexcept
Returns true if this component is the modal one.
bool isCurrentlyBlockedByAnotherModalComponent () const
Checks whether there's a modal component somewhere that's stopping this one from receiving messages.
virtual bool canModalEventBeSentToComponent (const Component *targetComponent)
When a component is modal, this callback allows it to choose which other components can still receive events.
virtual void inputAttemptWhenModal ()
Called when the user tries to click on a component that is blocked by another modal component.
NamedValueSet & getProperties () noexcept
Returns the set of properties that belong to this component.
const NamedValueSet & getProperties () const noexcept
Returns the set of properties that belong to this component.
Colour findColour (int colourId, bool inheritFromParent=false) const
Looks for a colour that has been registered with the given colour ID number.
void setColour (int colourId, const Colour &colour)
Registers a colour to be used for a particular purpose.
void removeColour (int colourId)
If a colour has been set with setColour(), this will remove it.
bool isColourSpecified (int colourId) const
Returns true if the specified colour ID has been explicitly set for this component using the setColour() method.
void copyAllExplicitColoursTo (Component &target) const
This looks for any colours that have been specified for this component, and copies them to the specified target component.
virtual void colourChanged ()
This method is called when a colour is changed by the setColour() method.
virtual MarkerList * getMarkers (bool xAxis)
Components can implement this method to provide a MarkerList.
void * getWindowHandle () const
Returns the underlying native window handle for this component.
Positioner * getPositioner () const noexcept
Returns the Positioner object that has been set for this component.
void setPositioner (Positioner *newPositioner)
Sets a new Positioner object for this component.
void setCachedComponentImage (CachedComponentImage *newCachedImage)
Gives the component a CachedComponentImage that should be used to buffer its painting.
CachedComponentImage * getCachedComponentImage () const noexcept
Returns the object that was set by setCachedComponentImage().
Public Member Functions inherited from MouseListener
virtual ~MouseListener ()
Destructor.
Protected Member Functions
void paint (Graphics &g)
void moved ()
(if overriding this, make sure you call ResizableWindow::moved() in your subclass)
void resized ()
(if overriding this, make sure you call ResizableWindow::resized() in your subclass)
void mouseDown (const MouseEvent &e)
void mouseDrag (const MouseEvent &e)
void lookAndFeelChanged ()
void childBoundsChanged (Component *child)
void parentSizeChanged ()
void visibilityChanged ()
void activeWindowStatusChanged ()
int getDesktopWindowStyleFlags () const
Protected Member Functions inherited from TopLevelWindow
void focusOfChildComponentChanged (FocusChangeType cause)
void parentHierarchyChanged ()
void recreateDesktopWindow ()
void visibilityChanged ()
Protected Attributes
ScopedPointer
< ResizableCornerComponent > resizableCorner
ScopedPointer
< ResizableBorderComponent > resizableBorder
Additional Inherited Members
Static Public Member Functions inherited from TopLevelWindow
static int getNumTopLevelWindows () noexcept
Returns the number of TopLevelWindow objects currently in use.
static TopLevelWindow * getTopLevelWindow (int index) noexcept
Returns one of the TopLevelWindow objects currently in use.
static TopLevelWindow * getActiveTopLevelWindow () noexcept
Returns the currently-active top level window.
Detailed Description
A base class for top-level windows that can be dragged around and resized.
To add content to the window, use its setContentOwned() or setContentNonOwned() methods to give it a component that will remain positioned inside it (leaving a gap around the edges for a border).
It's not advisable to add child components directly to a ResizableWindow: put them inside your content component instead. And overriding methods like resized(), moved(), etc is also not recommended - instead override these methods for your content component. (If for some obscure reason you do need to override these methods, always remember to call the super-class's resized() method too, otherwise it'll fail to lay out the window decorations correctly).
By default resizing isn't enabled - use the setResizable() method to enable it and to choose the style of resizing to use.
See Also
TopLevelWindow
Member Enumeration Documentation
enum ResizableWindow::ColourIds
A set of colour IDs to use to change the colour of various aspects of the window.
These constants can be used either via the Component::setColour(), or LookAndFeel::setColour() methods.
See Also
Component::setColour, Component::findColour, LookAndFeel::setColour, LookAndFeel::findColour
Enumerator:
backgroundColourId
A colour to use to fill the window's background.
Constructor & Destructor Documentation
ResizableWindow::ResizableWindow (const String & name, bool addToDesktop)
Creates a ResizableWindow.
This constructor doesn't specify a background colour, so the LookAndFeel's default background colour will be used.
Parameters
name the name to give the component
addToDesktop if true, the window will be automatically added to the desktop; if false, you can use it as a child component
ResizableWindow::ResizableWindow (const String & name, const Colour & backgroundColour, bool addToDesktop)
Creates a ResizableWindow.
Parameters
name the name to give the component
backgroundColour the colour to use for filling the window's background.
addToDesktop if true, the window will be automatically added to the desktop; if false, you can use it as a child component
ResizableWindow::~ResizableWindow ()
Destructor.
If a content component has been set with setContentOwned(), it will be deleted.
Member Function Documentation
Colour ResizableWindow::getBackgroundColour () const noexcept
Returns the colour currently being used for the window's background.
As a convenience the window will fill itself with this colour, but you can override the paint() method if you need more customised behaviour.
This method is the same as retrieving the colour for ResizableWindow::backgroundColourId.
See Also
setBackgroundColour
void ResizableWindow::setBackgroundColour (const Colour & newColour)
Changes the colour currently being used for the window's background.
As a convenience the window will fill itself with this colour, but you can override the paint() method if you need more customised behaviour.
Note that the opaque state of this window is altered by this call to reflect the opacity of the colour passed-in. On window systems which can't support semi-transparent windows this might cause problems, (though it's unlikely you'll be using this class as a base for a semi-transparent component anyway).
You can also use the ResizableWindow::backgroundColourId colour id to set this colour.
See Also
getBackgroundColour
void ResizableWindow::setResizable (bool shouldBeResizable, bool useBottomRightCornerResizer)
Make the window resizable or fixed.
Parameters
shouldBeResizable whether it's resizable at all
useBottomRightCornerResizer if true, it'll add a ResizableCornerComponent at the bottom-right; if false, it'll use a ResizableBorderComponent around the edge
See Also
setResizeLimits, isResizable
bool ResizableWindow::isResizable () const noexcept
True if resizing is enabled.
See Also
setResizable
void ResizableWindow::setResizeLimits (int newMinimumWidth, int newMinimumHeight, int newMaximumWidth, int newMaximumHeight) noexcept
This sets the maximum and minimum sizes for the window.
If the window's current size is outside these limits, it will be resized to make sure it's within them.
Calling setBounds() on the component will bypass any size checking - it's only when the window is being resized by the user that these values are enforced.
See Also
setResizable, setFixedAspectRatio
ComponentBoundsConstrainer* ResizableWindow::getConstrainer () noexcept
Returns the bounds constrainer object that this window is using.
You can access this to change its properties.
void ResizableWindow::setConstrainer (ComponentBoundsConstrainer * newConstrainer)
Sets the bounds-constrainer object to use for resizing and dragging this window.
A pointer to the object you pass in will be kept, but it won't be deleted by this object, so it's the caller's responsiblity to manage it.
If you pass 0, then no contraints will be placed on the positioning of the window.
void ResizableWindow::setBoundsConstrained (const Rectangle< int > & bounds)
Calls the window's setBounds method, after first checking these bounds with the current constrainer.
See Also
setConstrainer
Referenced by StandaloneFilterWindow::StandaloneFilterWindow().
bool ResizableWindow::isFullScreen () const
Returns true if the window is currently in full-screen mode.
See Also
setFullScreen
void ResizableWindow::setFullScreen (bool shouldBeFullScreen)
Puts the window into full-screen mode, or restores it to its normal size.
If true, the window will become full-screen; if false, it will return to the last size it was before being made full-screen.
See Also
isFullScreen
bool ResizableWindow::isMinimised () const
Returns true if the window is currently minimised.
See Also
setMinimised
void ResizableWindow::setMinimised (bool shouldMinimise)
Minimises the window, or restores it to its previous position and size.
When being un-minimised, it'll return to the last position and size it was in before being minimised.
See Also
isMinimised
void ResizableWindow::addToDesktop ()
Adds the window to the desktop using the default flags.
String ResizableWindow::getWindowStateAsString ()
Returns a string which encodes the window's current size and position.
This string will encapsulate the window's size, position, and whether it's in full-screen mode. It's intended for letting your application save and restore a window's position.
Use the restoreWindowStateFromString() to restore from a saved state.
See Also
restoreWindowStateFromString
bool ResizableWindow::restoreWindowStateFromString (const String & previousState)
Restores the window to a previously-saved size and position.
This restores the window's size, positon and full-screen status from an string that was previously created with the getWindowStateAsString() method.
Returns
false if the string wasn't a valid window state
See Also
getWindowStateAsString
Component* ResizableWindow::getContentComponent () const noexcept
Returns the current content component.
This will be the component set by setContentOwned() or setContentNonOwned, or nullptr if none has yet been specified.
See Also
setContentOwned, setContentNonOwned
void ResizableWindow::setContentOwned (Component * newContentComponent, bool resizeToFitWhenContentChangesSize)
Changes the current content component.
This sets a component that will be placed in the centre of the ResizableWindow, (leaving a space around the edge for the border).
You should never add components directly to a ResizableWindow (or any of its subclasses) with addChildComponent(). Instead, add them to the content component.
Parameters
newContentComponent the new component to use - this component will be deleted when it's no longer needed (i.e. when the window is deleted or a new content component is set for it). To set a component that this window will not delete, call setContentNonOwned() instead.
resizeToFitWhenContentChangesSize if true, then the ResizableWindow will maintain its size such that it always fits around the size of the content component. If false, the new content will be resized to fit the current space available.
Referenced by StandaloneFilterWindow::resetFilter(), and StandaloneFilterWindow::StandaloneFilterWindow().
void ResizableWindow::setContentNonOwned (Component * newContentComponent, bool resizeToFitWhenContentChangesSize)
Changes the current content component.
This sets a component that will be placed in the centre of the ResizableWindow, (leaving a space around the edge for the border).
You should never add components directly to a ResizableWindow (or any of its subclasses) with addChildComponent(). Instead, add them to the content component.
Parameters
newContentComponent the new component to use - this component will NOT be deleted by this component, so it's the caller's responsibility to manage its lifetime (it's ok to delete it while this window is still using it). To set a content component that the window will delete, call setContentOwned() instead.
resizeToFitWhenContentChangesSize if true, then the ResizableWindow will maintain its size such that it always fits around the size of the content component. If false, the new content will be resized to fit the current space available.
void ResizableWindow::clearContentComponent ()
Removes the current content component.
If the previous content component was added with setContentOwned(), it will also be deleted. If it was added with setContentNonOwned(), it will simply be removed from this component.
void ResizableWindow::setContentComponentSize (int width, int height)
Changes the window so that the content component ends up with the specified size.
This is basically a setSize call on the window, but which adds on the borders, so you can specify the content component's target size.
virtual BorderSize<int> ResizableWindow::getBorderThickness () virtual
Returns the width of the frame to use around the window.
See Also
getContentComponentBorder
virtual BorderSize<int> ResizableWindow::getContentComponentBorder () virtual
Returns the insets to use when positioning the content component.
See Also
getBorderThickness
ResizableWindow::JUCE_DEPRECATED (void setContentComponentComponent *newContentComponent, bool deleteOldOne=true, bool resizeToFit=false)
Deprecated:
use setContentOwned() and setContentNonOwned() instead.
void ResizableWindow::paint (Graphics & g) protected virtual
Reimplemented from Component.
void ResizableWindow::moved () protected virtual
(if overriding this, make sure you call ResizableWindow::moved() in your subclass)
Reimplemented from Component.
void ResizableWindow::resized () protected virtual
(if overriding this, make sure you call ResizableWindow::resized() in your subclass)
Reimplemented from Component.
Referenced by StandaloneFilterWindow::resized().
void ResizableWindow::mouseDown (const MouseEvent & e) protected virtual
Reimplemented from Component.
void ResizableWindow::mouseDrag (const MouseEvent & e) protected virtual
Reimplemented from Component.
void ResizableWindow::lookAndFeelChanged () protected virtual
Reimplemented from Component.
void ResizableWindow::childBoundsChanged (Component * child) protected virtual
Reimplemented from Component.
void ResizableWindow::parentSizeChanged () protected virtual
Reimplemented from Component.
void ResizableWindow::visibilityChanged () protected virtual
Reimplemented from Component.
void ResizableWindow::activeWindowStatusChanged () protected virtual
Reimplemented from TopLevelWindow.
int ResizableWindow::getDesktopWindowStyleFlags () const protected virtual
Reimplemented from TopLevelWindow.
Member Data Documentation
ScopedPointer<ResizableCornerComponent> ResizableWindow::resizableCorner protected
ScopedPointer<ResizableBorderComponent> ResizableWindow::resizableBorder protected
The documentation for this class was generated from the following file:
juce_ResizableWindow.h