JUCE: Quaternion< Type > Class Template Reference
Quaternion< Type > Class Template Reference
Holds a quaternion (a 3D vector and a scalar value).
Public Member Functions
Quaternion () noexcept
Quaternion (const Quaternion &other) noexcept
Quaternion (const Vector3D< Type > &vector_, const Type &scalar_) noexcept
Quaternion (const Type &x, const Type &y, const Type &z, const Type &w) noexcept
Quaternion & operator= (const Quaternion &other) noexcept
Quaternion & operator*= (const Quaternion &other) noexcept
Type length () const noexcept
Type normal () const noexcept
Quaternion normalised () const noexcept
Matrix3D< Type > getRotationMatrix () const noexcept
Returns the matrix that will perform the rotation specified by this quaternion.
Static Public Member Functions
static Quaternion fromAngle (const Type &angle, const Vector3D< Type > &axis) noexcept
Creates a quaternion from an angle and an axis.
Public Attributes
Vector3D< Type > vector
The vector part of the quaternion.
Type scalar
The scalar part of the quaternion.
Detailed Description
template<typename Type>
class Quaternion< Type >
Holds a quaternion (a 3D vector and a scalar value).
Constructor & Destructor Documentation
template<typename Type> Quaternion< Type >::Quaternion ()
Referenced by Quaternion< GLfloat >::fromAngle(), and Quaternion< GLfloat >::normalised().
template<typename Type> Quaternion< Type >::Quaternion (const Quaternion< Type > & other)
template<typename Type> Quaternion< Type >::Quaternion (const Vector3D< Type > & vector_, const Type & scalar_)
template<typename Type> Quaternion< Type >::Quaternion (const Type & x, const Type & y, const Type & z, const Type & w)
Member Function Documentation
template<typename Type> static Quaternion Quaternion< Type >::fromAngle (const Type & angle, const Vector3D< Type > & axis) [static]
Creates a quaternion from an angle and an axis.
template<typename Type> Quaternion& Quaternion< Type >::operator= (const Quaternion< Type > & other)
template<typename Type> Quaternion& Quaternion< Type >::operator*= (const Quaternion< Type > & other)
template<typename Type> Type Quaternion< Type >::length () const
Referenced by Quaternion< GLfloat >::normalised().
template<typename Type> Type Quaternion< Type >::normal () const
Referenced by Quaternion< GLfloat >::getRotationMatrix(), and Quaternion< GLfloat >::length().
template<typename Type> Quaternion Quaternion< Type >::normalised () const
template<typename Type> Matrix3D<Type> Quaternion< Type >::getRotationMatrix () const
Returns the matrix that will perform the rotation specified by this quaternion.
Referenced by Draggable3DOrientation::getRotationMatrix().
Member Data Documentation
template<typename Type> Vector3D<Type> Quaternion< Type >::vector
The vector part of the quaternion.
Referenced by Quaternion< GLfloat >::getRotationMatrix(), Quaternion< GLfloat >::normal(), Quaternion< GLfloat >::normalised(), Quaternion< GLfloat >::operator*=(), and Quaternion< GLfloat >::operator=().
template<typename Type> Type Quaternion< Type >::scalar
The scalar part of the quaternion.
Referenced by Quaternion< GLfloat >::getRotationMatrix(), Quaternion< GLfloat >::normal(), Quaternion< GLfloat >::normalised(), Quaternion< GLfloat >::operator*=(), and Quaternion< GLfloat >::operator=().
The documentation for this class was generated from the following file:
juce_Quaternion.h