JUCE: juce_String.h File Reference
juce_String.h File Reference
Classes
class String
The JUCE String class!
Functions
JUCE_API String JUCE_CALLTYPE operator+ (const char *string1, const String &string2)
Concatenates two strings.
JUCE_API String JUCE_CALLTYPE operator+ (const wchar_t *string1, const String &string2)
Concatenates two strings.
JUCE_API String JUCE_CALLTYPE operator+ (char string1, const String &string2)
Concatenates two strings.
JUCE_API String JUCE_CALLTYPE operator+ (wchar_t string1, const String &string2)
Concatenates two strings.
JUCE_API String JUCE_CALLTYPE operator+ (String string1, const String &string2)
Concatenates two strings.
JUCE_API String JUCE_CALLTYPE operator+ (String string1, const char *string2)
Concatenates two strings.
JUCE_API String JUCE_CALLTYPE operator+ (String string1, const wchar_t *string2)
Concatenates two strings.
JUCE_API String JUCE_CALLTYPE operator+ (String string1, char characterToAppend)
Concatenates two strings.
JUCE_API String JUCE_CALLTYPE operator+ (String string1, wchar_t characterToAppend)
Concatenates two strings.
JUCE_API String &JUCE_CALLTYPE operator<< (String &string1, char characterToAppend)
Appends a character at the end of a string.
JUCE_API String &JUCE_CALLTYPE operator<< (String &string1, wchar_t characterToAppend)
Appends a character at the end of a string.
JUCE_API String &JUCE_CALLTYPE operator<< (String &string1, const char *string2)
Appends a string to the end of the first one.
JUCE_API String &JUCE_CALLTYPE operator<< (String &string1, const wchar_t *string2)
Appends a string to the end of the first one.
JUCE_API String &JUCE_CALLTYPE operator<< (String &string1, const String &string2)
Appends a string to the end of the first one.
JUCE_API String &JUCE_CALLTYPE operator<< (String &string1, short number)
Appends a decimal number at the end of a string.
JUCE_API String &JUCE_CALLTYPE operator<< (String &string1, int number)
Appends a decimal number at the end of a string.
JUCE_API String &JUCE_CALLTYPE operator<< (String &string1, long number)
Appends a decimal number at the end of a string.
JUCE_API String &JUCE_CALLTYPE operator<< (String &string1, float number)
Appends a decimal number at the end of a string.
JUCE_API String &JUCE_CALLTYPE operator<< (String &string1, double number)
Appends a decimal number at the end of a string.
JUCE_API bool JUCE_CALLTYPE operator== (const String &string1, const String &string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator== (const String &string1, const char *string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator== (const String &string1, const wchar_t *string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator== (const String &string1, const CharPointer_UTF8 &string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator== (const String &string1, const CharPointer_UTF16 &string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator== (const String &string1, const CharPointer_UTF32 &string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator!= (const String &string1, const String &string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator!= (const String &string1, const char *string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator!= (const String &string1, const wchar_t *string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator!= (const String &string1, const CharPointer_UTF8 &string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator!= (const String &string1, const CharPointer_UTF16 &string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator!= (const String &string1, const CharPointer_UTF32 &string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator> (const String &string1, const String &string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator< (const String &string1, const String &string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator>= (const String &string1, const String &string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator<= (const String &string1, const String &string2) noexcept
Case-sensitive comparison of two strings.
template<class traits >
std::basic_ostream< char,
traits > &JUCE_CALLTYPE operator<< (std::basic_ostream< char, traits > &stream, const String &stringToWrite)
This operator allows you to write a juce String directly to std output streams.
template<class traits >
std::basic_ostream< wchar_t,
traits > &JUCE_CALLTYPE operator<< (std::basic_ostream< wchar_t, traits > &stream, const String &stringToWrite)
This operator allows you to write a juce String directly to std output streams.
JUCE_API OutputStream
&JUCE_CALLTYPE operator<< (OutputStream &stream, const String &stringToWrite)
Writes a string to an OutputStream as UTF8.
Function Documentation
JUCE_API String JUCE_CALLTYPE operator+ (const char * string1, const String & string2)
Concatenates two strings.
JUCE_API String JUCE_CALLTYPE operator+ (const wchar_t * string1, const String & string2)
Concatenates two strings.
JUCE_API String JUCE_CALLTYPE operator+ (char string1, const String & string2)
Concatenates two strings.
JUCE_API String JUCE_CALLTYPE operator+ (wchar_t string1, const String & string2)
Concatenates two strings.
JUCE_API String JUCE_CALLTYPE operator+ (String string1, const String & string2)
Concatenates two strings.
JUCE_API String JUCE_CALLTYPE operator+ (String string1, const char * string2)
Concatenates two strings.
JUCE_API String JUCE_CALLTYPE operator+ (String string1, const wchar_t * string2)
Concatenates two strings.
JUCE_API String JUCE_CALLTYPE operator+ (String string1, char characterToAppend)
Concatenates two strings.
JUCE_API String JUCE_CALLTYPE operator+ (String string1, wchar_t characterToAppend)
Concatenates two strings.
JUCE_API String& JUCE_CALLTYPE operator<< (String & string1, char characterToAppend)
Appends a character at the end of a string.
JUCE_API String& JUCE_CALLTYPE operator<< (String & string1, wchar_t characterToAppend)
Appends a character at the end of a string.
JUCE_API String& JUCE_CALLTYPE operator<< (String & string1, const char * string2)
Appends a string to the end of the first one.
JUCE_API String& JUCE_CALLTYPE operator<< (String & string1, const wchar_t * string2)
Appends a string to the end of the first one.
JUCE_API String& JUCE_CALLTYPE operator<< (String & string1, const String & string2)
Appends a string to the end of the first one.
JUCE_API String& JUCE_CALLTYPE operator<< (String & string1, short number)
Appends a decimal number at the end of a string.
JUCE_API String& JUCE_CALLTYPE operator<< (String & string1, int number)
Appends a decimal number at the end of a string.
JUCE_API String& JUCE_CALLTYPE operator<< (String & string1, long number)
Appends a decimal number at the end of a string.
JUCE_API String& JUCE_CALLTYPE operator<< (String & string1, float number)
Appends a decimal number at the end of a string.
JUCE_API String& JUCE_CALLTYPE operator<< (String & string1, double number)
Appends a decimal number at the end of a string.
JUCE_API bool JUCE_CALLTYPE operator== (const String & string1, const String & string2)
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator== (const String & string1, const char * string2)
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator== (const String & string1, const wchar_t * string2)
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator== (const String & string1, const CharPointer_UTF8 & string2)
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator== (const String & string1, const CharPointer_UTF16 & string2)
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator== (const String & string1, const CharPointer_UTF32 & string2)
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator!= (const String & string1, const String & string2)
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator!= (const String & string1, const char * string2)
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator!= (const String & string1, const wchar_t * string2)
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator!= (const String & string1, const CharPointer_UTF8 & string2)
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator!= (const String & string1, const CharPointer_UTF16 & string2)
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator!= (const String & string1, const CharPointer_UTF32 & string2)
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator> (const String & string1, const String & string2)
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator< (const String & string1, const String & string2)
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator>= (const String & string1, const String & string2)
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator<= (const String & string1, const String & string2)
Case-sensitive comparison of two strings.
template<class traits > std::basic_ostream<char, traits>& JUCE_CALLTYPE operator<< (std::basic_ostream< char, traits > & stream, const String & stringToWrite)
This operator allows you to write a juce String directly to std output streams.
This is handy for writing strings to std::cout, std::cerr, etc.
References CharPointer_UTF8::getAddress(), and String::toUTF8().
template<class traits > std::basic_ostream<wchar_t, traits>& JUCE_CALLTYPE operator<< (std::basic_ostream< wchar_t, traits > & stream, const String & stringToWrite)
This operator allows you to write a juce String directly to std output streams.
This is handy for writing strings to std::wcout, std::wcerr, etc.
References String::toWideCharPointer().
JUCE_API OutputStream& JUCE_CALLTYPE operator<< (OutputStream & stream, const String & stringToWrite)
Writes a string to an OutputStream as UTF8.