JUCE: AudioFormatWriter::WriteHelper< DestSampleType, SourceSampleType, DestEndianness > Struct Template Reference
AudioFormatWriter::WriteHelper< DestSampleType, SourceSampleType, DestEndianness > Struct Template Reference
Used by AudioFormatWriter subclasses to copy data to different formats.
Public Types
typedef AudioData::Pointer
< DestSampleType,
DestEndianness,
AudioData::Interleaved,
AudioData::NonConst > DestType
typedef AudioData::Pointer
< SourceSampleType,
AudioData::NativeEndian,
AudioData::NonInterleaved,
AudioData::Const > SourceType
Static Public Member Functions
static void write (void *destData, int numDestChannels, const int **source, int numSamples, const int sourceOffset=0) noexcept
Detailed Description
template<class DestSampleType, class SourceSampleType, class DestEndianness>
struct AudioFormatWriter::WriteHelper< DestSampleType, SourceSampleType, DestEndianness >
Used by AudioFormatWriter subclasses to copy data to different formats.
Member Typedef Documentation
template<class DestSampleType , class SourceSampleType , class DestEndianness > typedef AudioData::Pointer<DestSampleType, DestEndianness, AudioData::Interleaved, AudioData::NonConst> AudioFormatWriter::WriteHelper< DestSampleType, SourceSampleType, DestEndianness >::DestType
template<class DestSampleType , class SourceSampleType , class DestEndianness > typedef AudioData::Pointer<SourceSampleType, AudioData::NativeEndian, AudioData::NonInterleaved, AudioData::Const> AudioFormatWriter::WriteHelper< DestSampleType, SourceSampleType, DestEndianness >::SourceType
Member Function Documentation
template<class DestSampleType , class SourceSampleType , class DestEndianness > static void AudioFormatWriter::WriteHelper< DestSampleType, SourceSampleType, DestEndianness >::write (void * destData, int numDestChannels, const int ** source, int numSamples, const int sourceOffset = 0) [static]
References addBytesToPointer(), AudioData::Pointer< SampleFormat, Endianness, InterleavingType, Constness >::clearSamples(), and AudioData::Pointer< SampleFormat, Endianness, InterleavingType, Constness >::convertSamples().
The documentation for this struct was generated from the following file:
juce_AudioFormatWriter.h